---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  labels:
    app: movie-catalog-service
spec:
  type: NodePort
  selector:
    app: movie-catalog-service
  ports:
  - protocol: TCP
    port: 8081
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
spec:
  selector:
    matchLabels:
      app: movie-catalog-service
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue
        image: thetips4you/productcatalogue:latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
