---
apiVersion: v1
kind: Service
metadata:
  name: movie-info-service
  labels:
    app: movie-info-service
spec:
  type: NodePort
  selector:
    app: movie-info-service
  ports:
  - protocol: TCP
    port: 8082
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-service
spec:
  selector:
    matchLabels:
      app: movie-info-service
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-info-service
    spec:
      containers:
      - name: movie-info-service
        image: larisoft/movie-info-service:latest
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8082
          initialDelaySeconds: 30
          timeoutSeconds: 1
